package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	mycontext "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/context"
	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb"
	"github.com/MamangRust/monolith-graphql-payment-gateway-shared/domain/requests"
	sharedErrors "github.com/MamangRust/monolith-graphql-payment-gateway-shared/errors"
)

// VerifyCode is the resolver for the verifyCode field.
func (r *mutationResolver) VerifyCode(ctx context.Context, input model.VerifyCodeInput) (*model.APIResponseVerifyCode, error) {
	req := &pb.VerifyCodeRequest{
		Code: input.Code,
	}

	res, err := r.AuthGraphql.AuthClient.VerifyCode(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlVerifyCode(res)

	return so, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPasswordInput) (*model.APIResponseForgotPassword, error) {
	request := &requests.ForgotPasswordRequest{
		Email: input.Email,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.ForgotPasswordRequest{
		Email: input.Email,
	}

	res, err := r.AuthGraphql.AuthClient.ForgotPassword(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlForgotPassword(res)

	return so, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordInput) (*model.APIResponseResetPassword, error) {
	request := &requests.CreateResetPasswordRequest{
		ResetToken:      input.ResetToken,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.ResetPasswordRequest{
		ResetToken:      input.ResetToken,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	res, err := r.AuthGraphql.AuthClient.ResetPassword(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlResetPassword(res)

	return so, nil
}

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterInput) (*model.APIResponseRegister, error) {
	request := &requests.RegisterRequest{
		FirstName:       input.Firstname,
		LastName:        input.Lastname,
		Email:           input.Email,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.RegisterRequest{
		Firstname:       input.Firstname,
		Lastname:        input.Lastname,
		Email:           input.Email,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	res, err := r.AuthGraphql.AuthClient.RegisterUser(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlResponseRegister(res)

	return so, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input model.LoginInput) (*model.APIResponseLogin, error) {
	request := &requests.AuthRequest{
		Email:    input.Email,
		Password: input.Password,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	}

	res, err := r.AuthGraphql.AuthClient.LoginUser(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlResponseLogin(res)

	return so, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.APIResponseRefreshToken, error) {
	res, err := r.AuthGraphql.AuthClient.RefreshToken(ctx, &pb.RefreshTokenRequest{
		RefreshToken: input.RefreshToken,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlResponseRefreshToken(res)

	return so, nil
}

// GetMe is the resolver for the getMe field.
func (r *queryResolver) GetMe(ctx context.Context, input model.GetMeInput) (*model.APIResponseGetMe, error) {
	uid, ok := mycontext.UserForContext(ctx)

	if !ok || uid == 0 {
		return nil, fmt.Errorf("unauthorized: user ID not found in request context")
	}

	res, err := r.AuthGraphql.AuthClient.GetMe(ctx, &pb.GetMeRequest{UserId: int32(uid)})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.AuthGraphql.Mapping.ToGraphqlResponseGetMe(res)

	return so, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
