package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/card"
	pbstats "github.com/MamangRust/monolith-graphql-payment-gateway-pb/card/stats"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.CreateCardInput) (*model.APIResponseCard, error) {
	expireDate, err := time.Parse("2006-01-02", input.ExpireDate)
	if err != nil {
		return nil, fmt.Errorf("invalid date format for ExpireDate: %v (expected YYYY-MM-DD)", err)
	}

	req := &pb.CreateCardRequest{
		UserId:       int32(input.UserID),
		CardType:     input.CardType,
		ExpireDate:   timestamppb.New(expireDate),
		Cvv:          input.Cvv,
		CardProvider: input.CardProvider,
	}

	res, err := r.CardGraphql.CardClient.CardCommandClient.CreateCard(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)

	return so, nil
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, input model.UpdateCardInput) (*model.APIResponseCard, error) {
	expireDate, err := time.Parse("2006-01-02", input.ExpireDate)
	if err != nil {
		return nil, fmt.Errorf("invalid date format for ExpireDate: %v (expected YYYY-MM-DD)", err)
	}

	req := &pb.UpdateCardRequest{
		UserId:       int32(input.UserID),
		CardType:     input.CardType,
		ExpireDate:   timestamppb.New(expireDate),
		Cvv:          input.Cvv,
		CardProvider: input.CardProvider,
	}

	res, err := r.CardGraphql.CardClient.CardCommandClient.UpdateCard(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)

	return so, nil
}

// TrashedCard is the resolver for the trashedCard field.
func (r *mutationResolver) TrashedCard(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCardDeleteAt, error) {
	id := int32(input.CardID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidCardID
	}

	res, errResp := r.CardGraphql.CardClient.CardCommandClient.TrashedCard(ctx, &pb.FindByIdCardRequest{CardId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseCardDeleteAt(res)

	return so, nil
}

// RestoreCard is the resolver for the restoreCard field.
func (r *mutationResolver) RestoreCard(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCardDeleteAt, error) {
	id := int32(input.CardID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidCardID
	}

	res, errResp := r.CardGraphql.CardClient.CardCommandClient.RestoreCard(ctx, &pb.FindByIdCardRequest{CardId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseCardDeleteAt(res)

	return so, nil
}

// DeleteCardPermanent is the resolver for the deleteCardPermanent field.
func (r *mutationResolver) DeleteCardPermanent(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCardDelete, error) {
	id := int32(input.CardID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidCardID
	}

	res, errResp := r.CardGraphql.CardClient.CardCommandClient.DeleteCardPermanent(ctx, &pb.FindByIdCardRequest{CardId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseDelete(res)

	return so, nil
}

// RestoreAllCard is the resolver for the restoreAllCard field.
func (r *mutationResolver) RestoreAllCard(ctx context.Context) (*model.APIResponseCardAll, error) {
	res, errResp := r.CardGraphql.CardClient.CardCommandClient.DeleteAllCardPermanent(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseAll(res)

	return so, nil
}

// DeleteAllCardPermanent is the resolver for the deleteAllCardPermanent field.
func (r *mutationResolver) DeleteAllCardPermanent(ctx context.Context) (*model.APIResponseCardAll, error) {
	res, errResp := r.CardGraphql.CardClient.CardCommandClient.DeleteAllCardPermanent(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseAll(res)

	return so, nil
}

// FindAllCard is the resolver for the findAllCard field.
func (r *queryResolver) FindAllCard(ctx context.Context, input model.FindAllCardInput) (*model.APIResponsePaginationCard, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllCardRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, err := r.CardGraphql.CardClient.CardQueryClient.FindAllCard(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponsePaginationCard(res)

	return so, nil
}

// FindByIDCard is the resolver for the findByIdCard field.
func (r *queryResolver) FindByIDCard(ctx context.Context, input model.FindByIDCardInput) (*model.APIResponseCard, error) {
	id := int32(input.CardID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidCardID
	}

	card, err := r.CardGraphql.CardClient.CardQueryClient.FindByIdCard(ctx, &pb.FindByIdCardRequest{
		CardId: id,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseCard(card)

	return so, nil
}

// FindByUserIDCard is the resolver for the findByUserIdCard field.
func (r *queryResolver) FindByUserIDCard(ctx context.Context, input model.FindByUserIDCardInput) (*model.APIResponseCard, error) {
	id := int32(input.UserID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidUserID
	}

	res, err := r.CardGraphql.CardClient.CardQueryClient.FindByUserIdCard(ctx, &pb.FindByUserIdCardRequest{
		UserId: id,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponseCard(res)

	return so, nil
}

// FindByActiveCard is the resolver for the findByActiveCard field.
func (r *queryResolver) FindByActiveCard(ctx context.Context, input model.FindAllCardInput) (*model.APIResponsePaginationCardDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllCardRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, err := r.CardGraphql.CardClient.CardQueryClient.FindByActiveCard(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponsePaginationCardDeleteAt(res)

	return so, nil
}

// FindByTrashedCard is the resolver for the findByTrashedCard field.
func (r *queryResolver) FindByTrashedCard(ctx context.Context, input model.FindAllCardInput) (*model.APIResponsePaginationCardDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllCardRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, err := r.CardGraphql.CardClient.CardQueryClient.FindByTrashedCard(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlResponsePaginationCardDeleteAt(res)

	return so, nil
}

// FindByCardNumber is the resolver for the findByCardNumber field.
func (r *queryResolver) FindByCardNumber(ctx context.Context, input model.FindByCardNumberInput) (*model.APIResponseCard, error) {
	panic(fmt.Errorf("not implemented: FindByCardNumber - findByCardNumber"))
}

// DashboardCard is the resolver for the dashboardCard field.
func (r *queryResolver) DashboardCard(ctx context.Context) (*model.APIResponseDashboardCard, error) {
	dashboardCard, err := r.CardGraphql.CardClient.CardDashboardClient.DashboardCard(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlDashboardCard(dashboardCard)

	return so, nil
}

// DashboardCardNumber is the resolver for the dashboardCardNumber field.
func (r *queryResolver) DashboardCardNumber(ctx context.Context, input model.FindByCardNumberInput) (*model.APIResponseDashboardCardNumber, error) {
	cardNumber := input.CardNumber

	if cardNumber == "" {
		return nil, fmt.Errorf("card number cannot be empty")
	}

	dashboardCard, err := r.CardGraphql.CardClient.CardDashboardClient.DashboardCardNumber(ctx, &pb.FindByCardNumberRequest{
		CardNumber: cardNumber,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlDashboardCardCardNumber(dashboardCard)

	return so, nil
}

// FindMonthlyBalance is the resolver for the findMonthlyBalance field.
func (r *queryResolver) FindMonthlyBalance(ctx context.Context, input model.FindYearInput) (*model.APIResponseMonthlyBalance, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsBalanceClient.FindMonthlyBalance(ctx, &pbstats.FindYearBalance{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyBalances(res)

	return so, nil
}

// FindYearlyBalance is the resolver for the findYearlyBalance field.
func (r *queryResolver) FindYearlyBalance(ctx context.Context, input model.FindYearInput) (*model.APIResponseYearlyBalance, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsBalanceClient.FindYearlyBalance(ctx, &pbstats.FindYearBalance{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyBalances(res)

	return so, nil
}

// FindMonthlyTopupAmount is the resolver for the findMonthlyTopupAmount field.
func (r *queryResolver) FindMonthlyTopupAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTopupAmountClient.FindMonthlyTopupAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTopupAmount is the resolver for the findYearlyTopupAmount field.
func (r *queryResolver) FindYearlyTopupAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTopupAmountClient.FindYearlyTopupAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyWithdrawAmount is the resolver for the findMonthlyWithdrawAmount field.
func (r *queryResolver) FindMonthlyWithdrawAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsWithdrawAmountClient.FindMonthlyWithdrawAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyWithdrawAmount is the resolver for the findYearlyWithdrawAmount field.
func (r *queryResolver) FindYearlyWithdrawAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsWithdrawAmountClient.FindYearlyWithdrawAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTransactionAmount is the resolver for the findMonthlyTransactionAmount field.
func (r *queryResolver) FindMonthlyTransactionAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTransactionAmountClient.FindMonthlyTransactionAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTransactionAmount is the resolver for the findYearlyTransactionAmount field.
func (r *queryResolver) FindYearlyTransactionAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTransactionAmountClient.FindYearlyTransactionAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTransferSenderAmount is the resolver for the findMonthlyTransferSenderAmount field.
func (r *queryResolver) FindMonthlyTransferSenderAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindMonthlyTransferSenderAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTransferSenderAmount is the resolver for the findYearlyTransferSenderAmount field.
func (r *queryResolver) FindYearlyTransferSenderAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindYearlyTransferSenderAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTransferReceiverAmount is the resolver for the findMonthlyTransferReceiverAmount field.
func (r *queryResolver) FindMonthlyTransferReceiverAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindMonthlyTransferReceiverAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTransferReceiverAmount is the resolver for the findYearlyTransferReceiverAmount field.
func (r *queryResolver) FindYearlyTransferReceiverAmount(ctx context.Context, input model.FindYearInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindYearlyTransferReceiverAmount(ctx, &pb.FindYearAmount{
		Year: year,
	})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyBalanceByCardNumber is the resolver for the findMonthlyBalanceByCardNumber field.
func (r *queryResolver) FindMonthlyBalanceByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseMonthlyBalance, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pbstats.FindYearBalanceCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsBalanceClient.FindMonthlyBalanceByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyBalances(res)

	return so, nil
}

// FindYearlyBalanceByCardNumber is the resolver for the findYearlyBalanceByCardNumber field.
func (r *queryResolver) FindYearlyBalanceByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseYearlyBalance, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pbstats.FindYearBalanceCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsBalanceClient.FindYearlyBalanceByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyBalances(res)

	return so, nil
}

// FindMonthlyTopupAmountByCardNumber is the resolver for the findMonthlyTopupAmountByCardNumber field.
func (r *queryResolver) FindMonthlyTopupAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTopupAmountClient.FindMonthlyTopupAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTopupAmountByCardNumber is the resolver for the findYearlyTopupAmountByCardNumber field.
func (r *queryResolver) FindYearlyTopupAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTopupAmountClient.FindYearlyTopupAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyWithdrawAmountByCardNumber is the resolver for the findMonthlyWithdrawAmountByCardNumber field.
func (r *queryResolver) FindMonthlyWithdrawAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsWithdrawAmountClient.FindMonthlyWithdrawAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyWithdrawAmountByCardNumber is the resolver for the findYearlyWithdrawAmountByCardNumber field.
func (r *queryResolver) FindYearlyWithdrawAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsWithdrawAmountClient.FindYearlyWithdrawAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTransactionAmountByCardNumber is the resolver for the findMonthlyTransactionAmountByCardNumber field.
func (r *queryResolver) FindMonthlyTransactionAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransactionAmountClient.FindMonthlyTransactionAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTransactionAmountByCardNumber is the resolver for the findYearlyTransactionAmountByCardNumber field.
func (r *queryResolver) FindYearlyTransactionAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransactionAmountClient.FindYearlyTransactionAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTransferSenderAmountByCardNumber is the resolver for the findMonthlyTransferSenderAmountByCardNumber field.
func (r *queryResolver) FindMonthlyTransferSenderAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindMonthlyTransferSenderAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTransferSenderAmountByCardNumber is the resolver for the findYearlyTransferSenderAmountByCardNumber field.
func (r *queryResolver) FindYearlyTransferSenderAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindYearlyTransferSenderAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTransferReceiverAmountByCardNumber is the resolver for the findMonthlyTransferReceiverAmountByCardNumber field.
func (r *queryResolver) FindMonthlyTransferReceiverAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseMonthlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindMonthlyTransferReceiverAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyTransferReceiverAmountByCardNumber is the resolver for the findYearlyTransferReceiverAmountByCardNumber field.
func (r *queryResolver) FindYearlyTransferReceiverAmountByCardNumber(ctx context.Context, input model.FindYearCardNumberInput) (*model.APIResponseYearlyAmount, error) {
	year := int32(input.Year)
	card_number := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}
	if card_number == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	req := &pb.FindYearAmountCardNumber{
		Year:       year,
		CardNumber: card_number,
	}

	res, errResp := r.CardGraphql.CardClient.CardStatsTransferAmountClient.FindYearlyTransferReceiverAmountByCardNumber(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.CardGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}
