package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/merchant_document"
	"github.com/MamangRust/monolith-graphql-payment-gateway-shared/domain/requests"
	sharedErrors "github.com/MamangRust/monolith-graphql-payment-gateway-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateMerchantDocument is the resolver for the createMerchantDocument field.
func (r *mutationResolver) CreateMerchantDocument(ctx context.Context, input model.CreateMerchantDocumentInput) (*model.APIResponseMerchantDocument, error) {
	request := &requests.CreateMerchantDocumentRequest{
		MerchantID:   int(input.MerchantID),
		DocumentType: input.DocumentType,
		DocumentUrl:  input.DocumentURL,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.CreateMerchantDocumentRequest{
		MerchantId:   int32(input.MerchantID),
		DocumentType: input.DocumentType,
		DocumentUrl:  input.DocumentURL,
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.Create(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseMerchantDocument(res), nil
}

// UpdateMerchantDocument is the resolver for the updateMerchantDocument field.
func (r *mutationResolver) UpdateMerchantDocument(ctx context.Context, input model.UpdateMerchantDocumentInput) (*model.APIResponseMerchantDocument, error) {
	docId := int(input.DocumentID)

	if docId == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	request := &requests.UpdateMerchantDocumentRequest{
		DocumentID:   &docId,
		MerchantID:   int(input.MerchantID),
		DocumentType: input.DocumentType,
		DocumentUrl:  input.DocumentURL,
		Note:         *input.Note,
		Status:       *input.Status,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateMerchantDocumentRequest{
		DocumentId:   int32(input.DocumentID),
		MerchantId:   int32(input.MerchantID),
		DocumentType: input.DocumentType,
		DocumentUrl:  input.DocumentURL,
		Note:         *input.Note,
		Status:       *input.Status,
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.Update(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseMerchantDocument(res), nil
}

// UpdateMerchantDocumentStatus is the resolver for the updateMerchantDocumentStatus field.
func (r *mutationResolver) UpdateMerchantDocumentStatus(ctx context.Context, input model.UpdateMerchantDocumentStatusInput) (*model.APIResponseMerchantDocument, error) {
	docId := int(input.DocumentID)

	if docId == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	request := &requests.UpdateMerchantDocumentStatusRequest{
		DocumentID: &docId,
		MerchantID: int(input.MerchantID),
		Status:     *input.Status,
		Note:       *input.Note,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateMerchantDocumentStatusRequest{
		DocumentId: int32(input.DocumentID),
		MerchantId: int32(input.MerchantID),
		Note:       *input.Note,
		Status:     *input.Status,
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.UpdateStatus(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseMerchantDocument(res), nil
}

// TrashedMerchantDocument
func (r *mutationResolver) TrashedMerchantDocument(ctx context.Context, input model.TrashedMerchantDocumentInput) (*model.APIResponseMerchantDocumentDeleteAt, error) {
	req := &pb.FindMerchantDocumentByIdRequest{
		DocumentId: int32(input.DocumentID),
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.Trashed(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseMerchantDocumentDeleteAt(res), nil
}

// RestoreMerchantDocument
func (r *mutationResolver) RestoreMerchantDocument(ctx context.Context, input model.RestoreMerchantDocumentInput) (*model.APIResponseMerchantDocumentDeleteAt, error) {
	req := &pb.FindMerchantDocumentByIdRequest{
		DocumentId: int32(input.DocumentID),
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.Restore(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseMerchantDocumentDeleteAt(res), nil
}

// DeleteMerchantDocumentPermanent
func (r *mutationResolver) DeleteMerchantDocumentPermanent(ctx context.Context, input model.DeleteMerchantDocumentPermanentInput) (*model.APIResponseMerchantDocumentDelete, error) {
	req := &pb.FindMerchantDocumentByIdRequest{
		DocumentId: int32(input.DocumentID),
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.DeletePermanent(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseDelete(res), nil
}

// RestoreAllMerchantDocuments
func (r *mutationResolver) RestoreAllMerchantDocuments(ctx context.Context) (*model.APIResponseMerchantDocumentAll, error) {
	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.RestoreAll(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseAll(res), nil
}

// DeleteAllMerchantDocumentsPermanent
func (r *mutationResolver) DeleteAllMerchantDocumentsPermanent(ctx context.Context) (*model.APIResponseMerchantDocumentAll, error) {
	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentCommandClient.DeleteAllPermanent(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseAll(res), nil
}

// FindAllMerchantDocuments
func (r *queryResolver) FindAllMerchantDocuments(ctx context.Context, input model.FindAllMerchantDocumentsInput) (*model.APIResponsePaginationMerchantDocument, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantDocumentsRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentQueryClient.FindAll(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponsePaginationMerchantDocument(res), nil
}

// FindAllActiveMerchantDocuments
func (r *queryResolver) FindAllActiveMerchantDocuments(ctx context.Context, input model.FindAllMerchantDocumentsInput) (*model.APIResponsePaginationMerchantDocumentAt, error) {
	req := &pb.FindAllMerchantDocumentsRequest{
		Page:     int32(*input.Page),
		PageSize: int32(*input.PageSize),
		Search:   *input.Search,
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentQueryClient.FindAllActive(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponsePaginationMerchantDocumentDeleteAt(res), nil
}

// FindAllTrashedMerchantDocuments
func (r *queryResolver) FindAllTrashedMerchantDocuments(ctx context.Context, input model.FindAllMerchantDocumentsInput) (*model.APIResponsePaginationMerchantDocumentAt, error) {
	req := &pb.FindAllMerchantDocumentsRequest{
		Page:     int32(*input.Page),
		PageSize: int32(*input.PageSize),
		Search:   *input.Search,
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentQueryClient.FindAllTrashed(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponsePaginationMerchantDocumentDeleteAt(res), nil
}

// FindMerchantDocumentByID
func (r *queryResolver) FindMerchantDocumentByID(ctx context.Context, input model.FindMerchantDocumentByIDInput) (*model.APIResponseMerchantDocument, error) {
	req := &pb.FindMerchantDocumentByIdRequest{
		DocumentId: int32(input.DocumentID),
	}

	res, err := r.MerchantDocumentGraphql.MerchantClient.MerchantDocumentQueryClient.FindById(ctx, req)
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	return r.MerchantDocumentGraphql.Mapping.ToGraphqlResponseMerchantDocument(res), nil
}
