package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/merchant"
	"github.com/MamangRust/monolith-graphql-payment-gateway-shared/domain/requests"
	sharedErrors "github.com/MamangRust/monolith-graphql-payment-gateway-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateMerchant is the resolver for the createMerchant field.
func (r *mutationResolver) CreateMerchant(ctx context.Context, input model.CreateMerchantInput) (*model.APIResponseMerchant, error) {
	request := requests.CreateMerchantRequest{
		Name:   input.Name,
		UserID: int(input.UserID),
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.CreateMerchantRequest{
		Name:   input.Name,
		UserId: int32(input.UserID),
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.CreateMerchant(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)
	return so, nil
}

// UpdateMerchant is the resolver for the updateMerchant field.
func (r *mutationResolver) UpdateMerchant(ctx context.Context, input model.UpdateMerchantInput) (*model.APIResponseMerchant, error) {
	id := int(input.MerchantID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	request := requests.UpdateMerchantRequest{
		MerchantID: &id,
		Name:       input.Name,
		UserID:     int(input.UserID),
		Status:     input.Status,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateMerchantRequest{
		MerchantId: int32(id),
		Name:       input.Name,
		UserId:     input.UserID,
		Status:     input.Status,
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.UpdateMerchant(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)
	return so, nil
}

// UpdateMerchantStatus is the resolver for the updateMerchantStatus field.
func (r *mutationResolver) UpdateMerchantStatus(ctx context.Context, input model.UpdateMerchantStatusInput) (*model.APIResponseMerchant, error) {
	panic(fmt.Errorf("not implemented: UpdateMerchantStatus - updateMerchantStatus"))
}

// TrashedMerchant is the resolver for the trashedMerchant field.
func (r *mutationResolver) TrashedMerchant(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchantDeleteAt, error) {
	id := int32(input.MerchantID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.TrashedMerchant(ctx, &pb.FindByIdMerchantRequest{
		MerchantId: id,
	})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchantDeleteAt(merchant)
	return so, nil
}

// RestoreMerchant is the resolver for the restoreMerchant field.
func (r *mutationResolver) RestoreMerchant(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchantDeleteAt, error) {
	id := int32(input.MerchantID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.RestoreMerchant(ctx, &pb.FindByIdMerchantRequest{
		MerchantId: id,
	})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchantDeleteAt(merchant)
	return so, nil
}

// DeleteMerchantPermanent is the resolver for the deleteMerchantPermanent field.
func (r *mutationResolver) DeleteMerchantPermanent(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchantDelete, error) {
	id := int32(input.MerchantID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.DeleteMerchantPermanent(ctx, &pb.FindByIdMerchantRequest{
		MerchantId: id,
	})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMerchantDeleteAll(merchant)
	return so, nil
}

// RestoreAllMerchant is the resolver for the restoreAllMerchant field.
func (r *mutationResolver) RestoreAllMerchant(ctx context.Context) (*model.APIResponseMerchantAll, error) {
	res, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.RestoreAllMerchant(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMerchantAll(res)

	return so, nil
}

// DeleteAllMerchantPermanent is the resolver for the deleteAllMerchantPermanent field.
func (r *mutationResolver) DeleteAllMerchantPermanent(ctx context.Context) (*model.APIResponseMerchantAll, error) {
	res, errResp := r.MerchantGraphql.MerchantClient.MerchantCommand.DeleteAllMerchantPermanent(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMerchantAll(res)

	return so, nil
}

// FindAllMerchant is the resolver for the findAllMerchant field.
func (r *queryResolver) FindAllMerchant(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchant, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindAllMerchant(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationMerchant(res)

	return so, nil
}

// FindByIDMerchant is the resolver for the findByIdMerchant field.
func (r *queryResolver) FindByIDMerchant(ctx context.Context, input model.FindByIDMerchantInput) (*model.APIResponseMerchant, error) {
	id := int32(input.MerchantID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByIdMerchant(ctx, &pb.FindByIdMerchantRequest{MerchantId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)

	return so, nil
}

// FindByAPIKey is the resolver for the findByApiKey field.
func (r *queryResolver) FindByAPIKey(ctx context.Context, input model.FindByAPIKeyInput) (*model.APIResponseMerchant, error) {
	apiKey := input.APIKey
	if apiKey == "" {
		return nil, fmt.Errorf("api key is required")
	}

	merchant, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByApiKey(ctx, &pb.FindByApiKeyRequest{ApiKey: apiKey})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponseMerchant(merchant)
	return so, nil
}

// FindAllTransactionMerchant is the resolver for the findAllTransactionMerchant field.
func (r *queryResolver) FindAllTransactionMerchant(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchantTransaction, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantTransaction.FindAllTransactionMerchant(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationTransaction(res)

	return so, nil
}

// FindMonthlyPaymentMethodsMerchant is the resolver for the findMonthlyPaymentMethodsMerchant field.
func (r *queryResolver) FindMonthlyPaymentMethodsMerchant(ctx context.Context, input model.FindYearMerchantInput) (*model.APIResponseMerchantMonthlyPaymentMethod, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsMethod.FindMonthlyPaymentMethodsMerchant(ctx, &pb.FindYearMerchant{
		Year: year,
	})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyPaymentMethods(res)

	return so, nil
}

// FindYearlyPaymentMethodMerchant is the resolver for the findYearlyPaymentMethodMerchant field.
func (r *queryResolver) FindYearlyPaymentMethodMerchant(ctx context.Context, input model.FindYearMerchantInput) (*model.APIResponseMerchantYearlyPaymentMethod, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsMethod.FindYearlyPaymentMethodMerchant(ctx, &pb.FindYearMerchant{
		Year: year,
	})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyPaymentMethods(res)

	return so, nil
}

// FindMonthlyAmountMerchant is the resolver for the findMonthlyAmountMerchant field.
func (r *queryResolver) FindMonthlyAmountMerchant(ctx context.Context, input model.FindYearMerchantInput) (*model.APIResponseMerchantMonthlyAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsAmount.FindMonthlyAmountMerchant(ctx, &pb.FindYearMerchant{
		Year: year,
	})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyAmountMerchant is the resolver for the findYearlyAmountMerchant field.
func (r *queryResolver) FindYearlyAmountMerchant(ctx context.Context, input model.FindYearMerchantInput) (*model.APIResponseMerchantYearlyAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsAmount.FindYearlyAmountMerchant(ctx, &pb.FindYearMerchant{
		Year: year,
	})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTotalAmountMerchant is the resolver for the findMonthlyTotalAmountMerchant field.
func (r *queryResolver) FindMonthlyTotalAmountMerchant(ctx context.Context, input model.FindYearMerchantInput) (*model.APIResponseMerchantMonthlyTotalAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsTotalAmount.FindMonthlyTotalAmountMerchant(ctx, &pb.FindYearMerchant{
		Year: year,
	})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyTotalAmounts(res)

	return so, nil
}

// FindYearlyTotalAmountMerchant is the resolver for the findYearlyTotalAmountMerchant field.
func (r *queryResolver) FindYearlyTotalAmountMerchant(ctx context.Context, input model.FindYearMerchantInput) (*model.APIResponseMerchantYearlyTotalAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsTotalAmount.FindYearlyTotalAmountMerchant(ctx, &pb.FindYearMerchant{
		Year: year,
	})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyTotalAmounts(res)

	return so, nil
}

// FindAllTransactionByMerchant is the resolver for the findAllTransactionByMerchant field.
func (r *queryResolver) FindAllTransactionByMerchant(ctx context.Context, input model.FindAllMerchantTransactionInput) (*model.APIResponsePaginationMerchantTransaction, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search
	merchantId := int32(input.MerchantID)

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantTransaction{
		Page:       page,
		PageSize:   pageSize,
		Search:     *search,
		MerchantId: merchantId,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantTransaction.FindAllTransactionByMerchant(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationTransaction(res)

	return so, nil
}

// FindMonthlyPaymentMethodByMerchants is the resolver for the findMonthlyPaymentMethodByMerchants field.
func (r *queryResolver) FindMonthlyPaymentMethodByMerchants(ctx context.Context, input model.FindYearMerchantByIDInput) (*model.APIResponseMerchantMonthlyPaymentMethod, error) {
	year := int32(input.Year)
	merchantId := int32(input.MerchantID)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if merchantId <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	req := &pb.FindYearMerchantById{
		MerchantId: merchantId,
		Year:       year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsMethod.FindMonthlyPaymentMethodByMerchants(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyPaymentMethods(res)

	return so, nil
}

// FindYearlyPaymentMethodByMerchants is the resolver for the findYearlyPaymentMethodByMerchants field.
func (r *queryResolver) FindYearlyPaymentMethodByMerchants(ctx context.Context, input model.FindYearMerchantByIDInput) (*model.APIResponseMerchantYearlyPaymentMethod, error) {
	year := int32(input.Year)
	merchantId := int32(input.MerchantID)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if merchantId <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	req := &pb.FindYearMerchantById{
		MerchantId: merchantId,
		Year:       year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsMethod.FindYearlyPaymentMethodByMerchants(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyPaymentMethods(res)

	return so, nil
}

// FindMonthlyAmountByMerchants is the resolver for the findMonthlyAmountByMerchants field.
func (r *queryResolver) FindMonthlyAmountByMerchants(ctx context.Context, input model.FindYearMerchantByIDInput) (*model.APIResponseMerchantMonthlyAmount, error) {
	year := int32(input.Year)
	merchantId := int32(input.MerchantID)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if merchantId <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	req := &pb.FindYearMerchantById{
		MerchantId: merchantId,
		Year:       year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsAmount.FindMonthlyAmountByMerchants(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyAmountByMerchants is the resolver for the findYearlyAmountByMerchants field.
func (r *queryResolver) FindYearlyAmountByMerchants(ctx context.Context, input model.FindYearMerchantByIDInput) (*model.APIResponseMerchantYearlyAmount, error) {
	year := int32(input.Year)
	merchantId := int32(input.MerchantID)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if merchantId <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	req := &pb.FindYearMerchantById{
		MerchantId: merchantId,
		Year:       year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsAmount.FindYearlyAmountByMerchants(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTotalAmountByMerchants is the resolver for the findMonthlyTotalAmountByMerchants field.
func (r *queryResolver) FindMonthlyTotalAmountByMerchants(ctx context.Context, input model.FindYearMerchantByIDInput) (*model.APIResponseMerchantMonthlyTotalAmount, error) {
	year := int32(input.Year)
	merchantId := int32(input.MerchantID)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if merchantId <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	req := &pb.FindYearMerchantById{
		MerchantId: merchantId,
		Year:       year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsTotalAmount.FindMonthlyTotalAmountByMerchants(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyTotalAmounts(res)

	return so, nil
}

// FindYearlyTotalAmountByMerchants is the resolver for the findYearlyTotalAmountByMerchants field.
func (r *queryResolver) FindYearlyTotalAmountByMerchants(ctx context.Context, input model.FindYearMerchantByIDInput) (*model.APIResponseMerchantYearlyTotalAmount, error) {
	year := int32(input.Year)
	merchantId := int32(input.MerchantID)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if merchantId <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidID
	}

	req := &pb.FindYearMerchantById{
		MerchantId: merchantId,
		Year:       year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsTotalAmount.FindYearlyTotalAmountByMerchants(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyTotalAmounts(res)

	return so, nil
}

// FindAllTransactionByApikey is the resolver for the findAllTransactionByApikey field.
func (r *queryResolver) FindAllTransactionByApikey(ctx context.Context, input model.FindAllMerchantApikeyInput) (*model.APIResponsePaginationMerchantTransaction, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search
	apikey := input.APIKey

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantApikey{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
		ApiKey:   apikey,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantTransaction.FindAllTransactionByApikey(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationTransaction(res)

	return so, nil
}

// FindMonthlyPaymentMethodByApikey is the resolver for the findMonthlyPaymentMethodByApikey field.
func (r *queryResolver) FindMonthlyPaymentMethodByApikey(ctx context.Context, input model.FindYearMerchantByApikeyInput) (*model.APIResponseMerchantMonthlyPaymentMethod, error) {
	year := int32(input.Year)
	apiKey := input.APIKey

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if apiKey == "" {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidApiKey
	}

	req := &pb.FindYearMerchantByApikey{
		ApiKey: apiKey,
		Year:   year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsMethod.FindMonthlyPaymentMethodByApikey(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyPaymentMethods(res)

	return so, nil
}

// FindYearlyPaymentMethodByApikey is the resolver for the findYearlyPaymentMethodByApikey field.
func (r *queryResolver) FindYearlyPaymentMethodByApikey(ctx context.Context, input model.FindYearMerchantByApikeyInput) (*model.APIResponseMerchantYearlyPaymentMethod, error) {
	year := int32(input.Year)
	apiKey := input.APIKey

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if apiKey == "" {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidApiKey
	}

	req := &pb.FindYearMerchantByApikey{
		ApiKey: apiKey,
		Year:   year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsMethod.FindYearlyPaymentMethodByApikey(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyPaymentMethods(res)

	return so, nil
}

// FindMonthlyAmountByApikey is the resolver for the findMonthlyAmountByApikey field.
func (r *queryResolver) FindMonthlyAmountByApikey(ctx context.Context, input model.FindYearMerchantByApikeyInput) (*model.APIResponseMerchantMonthlyAmount, error) {
	year := int32(input.Year)
	apiKey := input.APIKey

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if apiKey == "" {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidApiKey
	}

	req := &pb.FindYearMerchantByApikey{
		ApiKey: apiKey,
		Year:   year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsAmount.FindMonthlyAmountByApikey(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyAmounts(res)

	return so, nil
}

// FindYearlyAmountByApikey is the resolver for the findYearlyAmountByApikey field.
func (r *queryResolver) FindYearlyAmountByApikey(ctx context.Context, input model.FindYearMerchantByApikeyInput) (*model.APIResponseMerchantYearlyAmount, error) {
	year := int32(input.Year)
	apiKey := input.APIKey

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if apiKey == "" {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidApiKey
	}

	req := &pb.FindYearMerchantByApikey{
		ApiKey: apiKey,
		Year:   year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsAmount.FindYearlyAmountByApikey(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyAmounts(res)

	return so, nil
}

// FindMonthlyTotalAmountByApikey is the resolver for the findMonthlyTotalAmountByApikey field.
func (r *queryResolver) FindMonthlyTotalAmountByApikey(ctx context.Context, input model.FindYearMerchantByApikeyInput) (*model.APIResponseMerchantMonthlyTotalAmount, error) {
	year := int32(input.Year)
	apiKey := input.APIKey

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if apiKey == "" {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidApiKey
	}

	req := &pb.FindYearMerchantByApikey{
		ApiKey: apiKey,
		Year:   year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsTotalAmount.FindMonthlyTotalAmountByApikey(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlMonthlyTotalAmounts(res)

	return so, nil
}

// FindYearlyTotalAmountByApikey is the resolver for the findYearlyTotalAmountByApikey field.
func (r *queryResolver) FindYearlyTotalAmountByApikey(ctx context.Context, input model.FindYearMerchantByApikeyInput) (*model.APIResponseMerchantYearlyTotalAmount, error) {
	year := int32(input.Year)
	apiKey := input.APIKey

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidYear
	}

	if apiKey == "" {
		return nil, graphqlerror.ErrGraphqlMerchantInvalidApiKey
	}

	req := &pb.FindYearMerchantByApikey{
		ApiKey: apiKey,
		Year:   year,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantStatsTotalAmount.FindYearlyTotalAmountByApikey(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlYearlyTotalAmounts(res)

	return so, nil
}

// FindByMerchantUserID is the resolver for the findByMerchantUserId field.
func (r *queryResolver) FindByMerchantUserID(ctx context.Context, input model.FindByMerchantUserIDInput) (*model.APIResponsesMerchant, error) {
	id := int32(input.UserID)
	if id == 0 {
		return nil, fmt.Errorf("invalid Merchant ID")
	}

	merchant, err := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByMerchantUserId(ctx, &pb.FindByMerchantUserIdRequest{UserId: id})
	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsesMerchant(merchant)

	return so, nil
}

// FindByActive is the resolver for the findByActive field.
func (r *queryResolver) FindByActive(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchantDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByActive(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationMerchantDeleteAt(res)

	return so, nil
}

// FindByTrashed is the resolver for the findByTrashed field.
func (r *queryResolver) FindByTrashed(ctx context.Context, input model.FindAllMerchantInput) (*model.APIResponsePaginationMerchantDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllMerchantRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.MerchantGraphql.MerchantClient.MerchantQuery.FindByTrashed(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.MerchantGraphql.Mapping.ToGraphqlResponsePaginationMerchantDeleteAt(res)

	return so, nil
}
