package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/role"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input model.CreateRoleInput) (*model.APIResponseRole, error) {
	req := &pb.CreateRoleRequest{
		Name: input.Name,
	}

	role, err := r.RoleGraphql.RoleClient.RoleCommandClient.CreateRole(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseRole(role)

	return so, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, input model.UpdateRoleInput) (*model.APIResponseRole, error) {
	roleId := int32(input.ID)

	if roleId == 0 {
		return nil, graphqlerror.ErrGraphqlRoleInvalidId
	}

	req := &pb.UpdateRoleRequest{
		Id:   roleId,
		Name: input.Name,
	}

	role, err := r.RoleGraphql.RoleClient.RoleCommandClient.UpdateRole(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseRole(role)

	return so, nil
}

// TrashedRole is the resolver for the trashedRole field.
func (r *mutationResolver) TrashedRole(ctx context.Context, input model.FindByIDRoleInput) (*model.APIResponseRoleDeleteAt, error) {
	roleID := int32(input.RoleID)

	if roleID == 0 {
		return nil, graphqlerror.ErrGraphqlRoleInvalidId
	}

	role, err := r.RoleGraphql.RoleClient.RoleCommandClient.TrashedRole(ctx, &pb.FindByIdRoleRequest{
		RoleId: roleID,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseRoleDeleteAt(role)

	return so, nil
}

// RestoreRole is the resolver for the restoreRole field.
func (r *mutationResolver) RestoreRole(ctx context.Context, input model.FindByIDRoleInput) (*model.APIResponseRoleDeleteAt, error) {
	roleID := int32(input.RoleID)

	if roleID == 0 {
		return nil, graphqlerror.ErrGraphqlRoleInvalidId
	}

	role, err := r.RoleGraphql.RoleClient.RoleCommandClient.RestoreRole(ctx, &pb.FindByIdRoleRequest{
		RoleId: roleID,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseRoleDeleteAt(role)

	return so, nil
}

// DeleteRolePermanent is the resolver for the deleteRolePermanent field.
func (r *mutationResolver) DeleteRolePermanent(ctx context.Context, input model.FindByIDRoleInput) (*model.APIResponseRoleDelete, error) {
	roleID := int32(input.RoleID)

	if roleID == 0 {
		return nil, graphqlerror.ErrGraphqlRoleInvalidId
	}

	role, err := r.RoleGraphql.RoleClient.RoleCommandClient.DeleteRolePermanent(ctx, &pb.FindByIdRoleRequest{
		RoleId: roleID,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseDelete(role)

	return so, nil
}

// RestoreAllRole is the resolver for the restoreAllRole field.
func (r *mutationResolver) RestoreAllRole(ctx context.Context) (*model.APIResponseRoleAll, error) {
	res, errResp := r.RoleGraphql.RoleClient.RoleCommandClient.RestoreAllRole(ctx, &emptypb.Empty{})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseAll(res)

	return so, nil
}

// DeleteAllRolePermanent is the resolver for the deleteAllRolePermanent field.
func (r *mutationResolver) DeleteAllRolePermanent(ctx context.Context) (*model.APIResponseRoleAll, error) {
	res, errResp := r.RoleGraphql.RoleClient.RoleCommandClient.DeleteAllRolePermanent(ctx, &emptypb.Empty{})

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseAll(res)

	return so, nil
}

// FindAllRole is the resolver for the findAllRole field.
func (r *queryResolver) FindAllRole(ctx context.Context, input model.FindAllRoleInput) (*model.APIResponsePaginationRole, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllRoleRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.RoleGraphql.RoleClient.RoleQueryClient.FindAllRole(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponsePaginationRole(res)

	return so, nil
}

// FindByIDRole is the resolver for the findByIdRole field.
func (r *queryResolver) FindByIDRole(ctx context.Context, input model.FindByIDRoleInput) (*model.APIResponseRole, error) {
	id := int32(input.RoleID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlRoleInvalidUserId
	}

	role, errResp := r.RoleGraphql.RoleClient.RoleQueryClient.FindByIdRole(ctx, &pb.FindByIdRoleRequest{RoleId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponseRole(role)

	return so, nil
}

// FindByActiveRole is the resolver for the findByActiveRole field.
func (r *queryResolver) FindByActiveRole(ctx context.Context, input model.FindAllRoleInput) (*model.APIResponsePaginationRoleDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllRoleRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.RoleGraphql.RoleClient.RoleQueryClient.FindByActive(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponsePaginationRoleDeleteAt(res)

	return so, nil
}

// FindByTrashedRole is the resolver for the findByTrashedRole field.
func (r *queryResolver) FindByTrashedRole(ctx context.Context, input model.FindAllRoleInput) (*model.APIResponsePaginationRoleDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllRoleRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	res, errResp := r.RoleGraphql.RoleClient.RoleQueryClient.FindByTrashed(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponsePaginationRoleDeleteAt(res)

	return so, nil
}

// FindByUserIDRole is the resolver for the findByUserIdRole field.
func (r *queryResolver) FindByUserIDRole(ctx context.Context, input model.FindByUserIDRoleInput) (*model.APIResponsesRole, error) {
	id := int32(input.UserID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlRoleInvalidUserId
	}

	role, errResp := r.RoleGraphql.RoleClient.RoleQueryClient.FindByUserId(ctx, &pb.FindByIdUserRoleRequest{UserId: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.RoleGraphql.Mapping.ToGraphqlResponsesRole(role)

	return so, nil
}
