package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pbcard "github.com/MamangRust/monolith-graphql-payment-gateway-pb/card"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/saldo"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateSaldo is the resolver for the createSaldo field.
func (r *mutationResolver) CreateSaldo(ctx context.Context, input model.CreateSaldoInput) (*model.APIResponseSaldo, error) {
	request := &pb.CreateSaldoRequest{
		CardNumber:   input.CardNumber,
		TotalBalance: int32(input.TotalBalance),
	}

	saldo, err := r.SaldoGraphql.SaldoClient.SaldoCommandClient.CreateSaldo(ctx, request)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseSaldo(saldo)

	return so, nil
}

// UpdateSaldo is the resolver for the updateSaldo field.
func (r *mutationResolver) UpdateSaldo(ctx context.Context, input model.UpdateSaldoInput) (*model.APIResponseSaldo, error) {
	id := int32(input.SaldoID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidID
	}

	request := &pb.UpdateSaldoRequest{
		SaldoId:      id,
		CardNumber:   input.CardNumber,
		TotalBalance: int32(input.TotalBalance),
	}

	saldo, err := r.SaldoGraphql.SaldoClient.SaldoCommandClient.UpdateSaldo(ctx, request)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseSaldo(saldo)

	return so, nil
}

// TrashedSaldo is the resolver for the trashedSaldo field.
func (r *mutationResolver) TrashedSaldo(ctx context.Context, input model.FindByIDSaldoInput) (*model.APIResponseSaldoDeleteAt, error) {
	id := int32(input.SaldoID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidID
	}

	saldo, err := r.SaldoGraphql.SaldoClient.SaldoCommandClient.TrashedSaldo(ctx, &pb.FindByIdSaldoRequest{SaldoId: id})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseSaldoDeleteAt(saldo)

	return so, nil
}

// RestoreSaldo is the resolver for the restoreSaldo field.
func (r *mutationResolver) RestoreSaldo(ctx context.Context, input model.FindByIDSaldoInput) (*model.APIResponseSaldoDeleteAt, error) {
	id := int32(input.SaldoID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidID
	}

	saldo, err := r.SaldoGraphql.SaldoClient.SaldoCommandClient.RestoreSaldo(ctx, &pb.FindByIdSaldoRequest{SaldoId: id})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseSaldoDeleteAt(saldo)

	return so, nil
}

// DeleteSaldoPermanent is the resolver for the deleteSaldoPermanent field.
func (r *mutationResolver) DeleteSaldoPermanent(ctx context.Context, input model.FindByIDSaldoInput) (*model.APIResponseSaldoDelete, error) {
	id := int32(input.SaldoID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidID
	}

	res, err := r.SaldoGraphql.SaldoClient.SaldoCommandClient.DeleteSaldoPermanent(ctx, &pb.FindByIdSaldoRequest{
		SaldoId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseDelete(res)

	return so, nil
}

// RestoreAllSaldo is the resolver for the restoreAllSaldo field.
func (r *mutationResolver) RestoreAllSaldo(ctx context.Context) (*model.APIResponseSaldoAll, error) {
	res, errResp := r.SaldoGraphql.SaldoClient.SaldoCommandClient.RestoreAllSaldo(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseAll(res)

	return so, nil
}

// DeleteAllSaldoPermanent is the resolver for the deleteAllSaldoPermanent field.
func (r *mutationResolver) DeleteAllSaldoPermanent(ctx context.Context) (*model.APIResponseSaldoAll, error) {
	res, errResp := r.SaldoGraphql.SaldoClient.SaldoCommandClient.DeleteAllSaldoPermanent(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseAll(res)

	return so, nil
}

// FindAllSaldo is the resolver for the findAllSaldo field.
func (r *queryResolver) FindAllSaldo(ctx context.Context, input model.FindAllSaldoInput) (*model.APIResponsePaginationSaldo, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllSaldoRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	saldos, errResp := r.SaldoGraphql.SaldoClient.SaldoQueryClient.FindAllSaldo(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponsePaginationSaldo(saldos)

	return so, nil
}

// FindByIDSaldo is the resolver for the findByIdSaldo field.
func (r *queryResolver) FindByIDSaldo(ctx context.Context, input model.FindByIDSaldoInput) (*model.APIResponseSaldo, error) {
	id := int32(input.SaldoID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidID
	}

	saldo, err := r.SaldoGraphql.SaldoClient.SaldoQueryClient.FindByIdSaldo(ctx, &pb.FindByIdSaldoRequest{SaldoId: id})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseSaldo(saldo)

	return so, nil
}

// FindMonthlyTotalSaldoBalance is the resolver for the findMonthlyTotalSaldoBalance field.
func (r *queryResolver) FindMonthlyTotalSaldoBalance(ctx context.Context, input model.FindMonthlySaldoTotalBalanceInput) (*model.APIResponseMonthTotalSaldo, error) {
	year := int32(input.Year)
	month := int32(input.Month)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidMonth
	}

	reqService := &pb.FindMonthlySaldoTotalBalance{
		Year:  year,
		Month: month,
	}

	res, err := r.SaldoGraphql.SaldoClient.SaldoStatsTotalBalanceClient.FindMonthlyTotalSaldoBalance(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseMonthTotalSaldo(res)

	return so, nil
}

// FindYearTotalSaldoBalance is the resolver for the findYearTotalSaldoBalance field.
func (r *queryResolver) FindYearTotalSaldoBalance(ctx context.Context, input model.FindYearlySaldoInput) (*model.APIResponseYearTotalSaldo, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidYear
	}

	reqService := &pb.FindYearlySaldo{
		Year: year,
	}

	res, err := r.SaldoGraphql.SaldoClient.SaldoStatsTotalBalanceClient.FindYearTotalSaldoBalance(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseYearTotalSaldo(res)

	return so, nil
}

// FindMonthlySaldoBalances is the resolver for the findMonthlySaldoBalances field.
func (r *queryResolver) FindMonthlySaldoBalances(ctx context.Context, input model.FindYearlySaldoInput) (*model.APIResponseMonthSaldoBalances, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidYear
	}

	reqService := &pb.FindYearlySaldo{
		Year: year,
	}

	res, err := r.SaldoGraphql.SaldoClient.SaldoStatsBalanceClient.FindMonthlySaldoBalances(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseMonthSaldoBalances(res)

	return so, nil
}

// FindYearlySaldoBalances is the resolver for the findYearlySaldoBalances field.
func (r *queryResolver) FindYearlySaldoBalances(ctx context.Context, input model.FindYearlySaldoInput) (*model.APIResponseYearSaldoBalances, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidYear
	}

	reqService := &pb.FindYearlySaldo{
		Year: year,
	}

	res, err := r.SaldoGraphql.SaldoClient.SaldoStatsBalanceClient.FindYearlySaldoBalances(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseYearBalance(res)

	return so, nil
}

// FindByCardNumberSaldo is the resolver for the findByCardNumberSaldo field.
func (r *queryResolver) FindByCardNumberSaldo(ctx context.Context, cardNumber string) (*model.APIResponseSaldo, error) {
	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlSaldoInvalidCardNumber
	}

	saldo, err := r.SaldoGraphql.SaldoClient.SaldoQueryClient.FindByCardNumber(ctx, &pbcard.FindByCardNumberRequest{
		CardNumber: cardNumber,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponseSaldo(saldo)

	return so, nil
}

// FindByActiveSaldo is the resolver for the findByActiveSaldo field.
func (r *queryResolver) FindByActiveSaldo(ctx context.Context, input model.FindAllSaldoInput) (*model.APIResponsePaginationSaldoDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllSaldoRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	saldos, errResp := r.SaldoGraphql.SaldoClient.SaldoQueryClient.FindByActive(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponsePaginationSaldoDeleteAt(saldos)

	return so, nil
}

// FindByTrashedSaldo is the resolver for the findByTrashedSaldo field.
func (r *queryResolver) FindByTrashedSaldo(ctx context.Context, input model.FindAllSaldoInput) (*model.APIResponsePaginationSaldoDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllSaldoRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	saldos, errResp := r.SaldoGraphql.SaldoClient.SaldoQueryClient.FindByTrashed(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.SaldoGraphql.Mapping.ToGraphqlResponsePaginationSaldoDeleteAt(saldos)

	return so, nil
}
