package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/topup"
	"github.com/MamangRust/monolith-graphql-payment-gateway-shared/domain/requests"
	sharedErrors "github.com/MamangRust/monolith-graphql-payment-gateway-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateTopup is the resolver for the createTopup field.
func (r *mutationResolver) CreateTopup(ctx context.Context, input model.CreateTopupInput) (*model.APIResponseTopup, error) {
	request := &requests.CreateTopupRequest{
		CardNumber:  input.CardNumber,
		TopupAmount: int(input.TopupAmount),
		TopupMethod: input.TopupMethod,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.CreateTopupRequest{
		CardNumber:  input.CardNumber,
		TopupAmount: int32(input.TopupAmount),
		TopupMethod: input.TopupMethod,
	}

	res, err := r.TopupGraphql.TopupClient.TopupCommandClient.CreateTopup(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(res)

	return so, nil
}

// UpdateTopup is the resolver for the updateTopup field.
func (r *mutationResolver) UpdateTopup(ctx context.Context, input model.UpdateTopupInput) (*model.APIResponseTopup, error) {
	id := int(input.TopupID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidID
	}

	request := &requests.UpdateTopupRequest{
		TopupID:     &id,
		CardNumber:  input.CardNumber,
		TopupAmount: int(input.TopupAmount),
		TopupMethod: input.TopupMethod,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateTopupRequest{
		TopupId:     int32(id),
		CardNumber:  input.CardNumber,
		TopupAmount: int32(input.TopupAmount),
		TopupMethod: input.TopupMethod,
	}

	res, err := r.TopupGraphql.TopupClient.TopupCommandClient.UpdateTopup(ctx, req)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(res)

	return so, nil
}

// TrashedTopup is the resolver for the trashedTopup field.
func (r *mutationResolver) TrashedTopup(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopupDeleteAt, error) {
	id := int32(input.TopupID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidID
	}

	topup, err := r.TopupGraphql.TopupClient.TopupCommandClient.TrashedTopup(ctx, &pb.FindByIdTopupRequest{
		TopupId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupDeleteAt(topup)

	return so, nil
}

// RestoreTopup is the resolver for the restoreTopup field.
func (r *mutationResolver) RestoreTopup(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopupDeleteAt, error) {
	id := int32(input.TopupID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidID
	}

	topup, err := r.TopupGraphql.TopupClient.TopupCommandClient.RestoreTopup(ctx, &pb.FindByIdTopupRequest{
		TopupId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupDeleteAt(topup)

	return so, nil
}

// DeleteTopupPermanent is the resolver for the deleteTopupPermanent field.
func (r *mutationResolver) DeleteTopupPermanent(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopupDelete, error) {
	id := int32(input.TopupID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidID
	}
	res, err := r.TopupGraphql.TopupClient.TopupCommandClient.DeleteTopupPermanent(ctx, &pb.FindByIdTopupRequest{TopupId: id})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlTopupDelete(res)

	return so, nil
}

// RestoreAllTopup is the resolver for the restoreAllTopup field.
func (r *mutationResolver) RestoreAllTopup(ctx context.Context) (*model.APIResponseTopupAll, error) {
	res, err := r.TopupGraphql.TopupClient.TopupCommandClient.RestoreAllTopup(ctx, &emptypb.Empty{})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlTopupAll(res)

	return so, nil
}

// DeleteAllTopupPermanent is the resolver for the deleteAllTopupPermanent field.
func (r *mutationResolver) DeleteAllTopupPermanent(ctx context.Context) (*model.APIResponseTopupAll, error) {
	res, err := r.TopupGraphql.TopupClient.TopupCommandClient.DeleteAllTopupPermanent(ctx, &emptypb.Empty{})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlTopupAll(res)

	return so, nil
}

// FindAllTopup is the resolver for the findAllTopup field.
func (r *queryResolver) FindAllTopup(ctx context.Context, input model.FindAllTopupInput) (*model.APIResponsePaginationTopup, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllTopupRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindAllTopup(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopup(topups)

	return so, nil
}

// FindAllTopupByCardNumber is the resolver for the findAllTopupByCardNumber field.
func (r *queryResolver) FindAllTopupByCardNumber(ctx context.Context, input model.FindAllTopupByCardNumberInput) (*model.APIResponsePaginationTopup, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search
	cardNumber := input.CardNumber

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllTopupByCardNumberRequest{
		Page:       page,
		PageSize:   pageSize,
		Search:     *search,
		CardNumber: cardNumber,
	}

	topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindAllTopupByCardNumber(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopup(topups)

	return so, nil
}

// FindByIDTopup is the resolver for the findByIdTopup field.
func (r *queryResolver) FindByIDTopup(ctx context.Context, input model.FindByIDTopupInput) (*model.APIResponseTopup, error) {
	id := int32(input.TopupID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidID
	}

	topup, err := r.TopupGraphql.TopupClient.TopupQueryClient.FindByIdTopup(ctx, &pb.FindByIdTopupRequest{TopupId: id})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopup(topup)

	return so, nil
}

// FindMonthlyTopupStatusSuccess is the resolver for the findMonthlyTopupStatusSuccess field.
func (r *queryResolver) FindMonthlyTopupStatusSuccess(ctx context.Context, input model.FindMonthlyTopupStatusInput) (*model.APIResponseTopupMonthStatusSuccess, error) {
	year := int32(input.Year)
	month := int32(input.Month)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidMonth
	}

	reqService := &pb.FindMonthlyTopupStatus{
		Year:  year,
		Month: month,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindMonthlyTopupStatusSuccess(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthStatusSuccess(res)

	return so, nil
}

// FindYearlyTopupStatusSuccess is the resolver for the findYearlyTopupStatusSuccess field.
func (r *queryResolver) FindYearlyTopupStatusSuccess(ctx context.Context, input model.FindYearTopupStatusInput) (*model.APIResponseTopupYearStatusSuccess, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindYearlyTopupStatusSuccess(ctx, &pb.FindYearTopupStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearStatusSuccess(res)

	return so, nil
}

// FindMonthlyTopupStatusFailed is the resolver for the findMonthlyTopupStatusFailed field.
func (r *queryResolver) FindMonthlyTopupStatusFailed(ctx context.Context, input model.FindMonthlyTopupStatusInput) (*model.APIResponseTopupMonthStatusFailed, error) {
	year := int32(input.Year)
	month := int32(input.Month)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidMonth
	}

	reqService := &pb.FindMonthlyTopupStatus{
		Year:  year,
		Month: month,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindMonthlyTopupStatusFailed(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthStatusFailed(res)

	return so, nil
}

// FindYearlyTopupStatusFailed is the resolver for the findYearlyTopupStatusFailed field.
func (r *queryResolver) FindYearlyTopupStatusFailed(ctx context.Context, input model.FindYearTopupStatusInput) (*model.APIResponseTopupYearStatusFailed, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindYearlyTopupStatusFailed(ctx, &pb.FindYearTopupStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearStatusFailed(res)

	return so, nil
}

// FindMonthlyTopupStatusSuccessByCardNumber is the resolver for the findMonthlyTopupStatusSuccessByCardNumber field.
func (r *queryResolver) FindMonthlyTopupStatusSuccessByCardNumber(ctx context.Context, input model.FindMonthlyTopupStatusCardNumberInput) (*model.APIResponseTopupMonthStatusSuccess, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindMonthlyTopupStatusCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindMonthlyTopupStatusSuccessByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthStatusSuccess(res)

	return so, nil
}

// FindYearlyTopupStatusSuccessByCardNumber is the resolver for the findYearlyTopupStatusSuccessByCardNumber field.
func (r *queryResolver) FindYearlyTopupStatusSuccessByCardNumber(ctx context.Context, input model.FindYearTopupStatusCardNumberInput) (*model.APIResponseTopupYearStatusSuccess, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTopupStatusCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindYearlyTopupStatusSuccessByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearStatusSuccess(res)

	return so, nil
}

// FindMonthlyTopupStatusFailedByCardNumber is the resolver for the findMonthlyTopupStatusFailedByCardNumber field.
func (r *queryResolver) FindMonthlyTopupStatusFailedByCardNumber(ctx context.Context, input model.FindMonthlyTopupStatusCardNumberInput) (*model.APIResponseTopupMonthStatusFailed, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindMonthlyTopupStatusCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindMonthlyTopupStatusFailedByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthStatusFailed(res)

	return so, nil
}

// FindYearlyTopupStatusFailedByCardNumber is the resolver for the findYearlyTopupStatusFailedByCardNumber field.
func (r *queryResolver) FindYearlyTopupStatusFailedByCardNumber(ctx context.Context, input model.FindYearTopupStatusCardNumberInput) (*model.APIResponseTopupYearStatusFailed, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTopupStatusCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsStatus.FindYearlyTopupStatusFailedByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearStatusFailed(res)

	return so, nil
}

// FindMonthlyTopupMethods is the resolver for the findMonthlyTopupMethods field.
func (r *queryResolver) FindMonthlyTopupMethods(ctx context.Context, input model.FindYearTopupStatusInput) (*model.APIResponseTopupMonthMethod, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsMethod.FindMonthlyTopupMethods(ctx, &pb.FindYearTopupStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthMethod(res)

	return so, nil
}

// FindYearlyTopupMethods is the resolver for the findYearlyTopupMethods field.
func (r *queryResolver) FindYearlyTopupMethods(ctx context.Context, input model.FindYearTopupStatusInput) (*model.APIResponseTopupYearMethod, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsMethod.FindYearlyTopupMethods(ctx, &pb.FindYearTopupStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearMethod(res)

	return so, nil
}

// FindMonthlyTopupAmounts is the resolver for the findMonthlyTopupAmounts field.
func (r *queryResolver) FindMonthlyTopupAmounts(ctx context.Context, input model.FindYearTopupStatusInput) (*model.APIResponseTopupMonthAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsAmount.FindMonthlyTopupAmounts(ctx, &pb.FindYearTopupStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthAmount(res)

	return so, nil
}

// FindYearlyTopupAmounts is the resolver for the findYearlyTopupAmounts field.
func (r *queryResolver) FindYearlyTopupAmounts(ctx context.Context, input model.FindYearTopupStatusInput) (*model.APIResponseTopupYearAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsAmount.FindYearlyTopupAmounts(ctx, &pb.FindYearTopupStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearAmount(res)

	return so, nil
}

// FindMonthlyTopupMethodsByCardNumber is the resolver for the findMonthlyTopupMethodsByCardNumber field.
func (r *queryResolver) FindMonthlyTopupMethodsByCardNumber(ctx context.Context, input model.FindYearTopupCardNumberInput) (*model.APIResponseTopupMonthMethod, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTopupCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsMethod.FindMonthlyTopupMethodsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthMethod(res)

	return so, nil
}

// FindYearlyTopupMethodsByCardNumber is the resolver for the findYearlyTopupMethodsByCardNumber field.
func (r *queryResolver) FindYearlyTopupMethodsByCardNumber(ctx context.Context, input model.FindYearTopupCardNumberInput) (*model.APIResponseTopupYearMethod, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTopupCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsMethod.FindYearlyTopupMethodsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearMethod(res)

	return so, nil
}

// FindMonthlyTopupAmountsByCardNumber is the resolver for the findMonthlyTopupAmountsByCardNumber field.
func (r *queryResolver) FindMonthlyTopupAmountsByCardNumber(ctx context.Context, input model.FindYearTopupCardNumberInput) (*model.APIResponseTopupMonthAmount, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTopupCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsAmount.FindMonthlyTopupAmountsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupMonthAmount(res)

	return so, nil
}

// FindYearlyTopupAmountsByCardNumber is the resolver for the findYearlyTopupAmountsByCardNumber field.
func (r *queryResolver) FindYearlyTopupAmountsByCardNumber(ctx context.Context, input model.FindYearTopupCardNumberInput) (*model.APIResponseTopupYearAmount, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlTopupInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTopupCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TopupGraphql.TopupClient.TopupStatsAmount.FindYearlyTopupAmountsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponseTopupYearAmount(res)

	return so, nil
}

// FindByCardNumberTopup is the resolver for the findByCardNumberTopup field.
func (r *queryResolver) FindByCardNumberTopup(ctx context.Context, input model.FindByCardNumberTopupInput) (*model.APIResponseTopup, error) {
	panic(fmt.Errorf("not implemented: FindByCardNumberTopup - findByCardNumberTopup"))
}

// FindByActiveTopup is the resolver for the findByActiveTopup field.
func (r *queryResolver) FindByActiveTopup(ctx context.Context, input model.FindAllTopupInput) (*model.APIResponsePaginationTopupDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllTopupRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindByActive(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopupDeleteAt(topups)

	return so, nil
}

// FindByTrashedTopup is the resolver for the findByTrashedTopup field.
func (r *queryResolver) FindByTrashedTopup(ctx context.Context, input model.FindAllTopupInput) (*model.APIResponsePaginationTopupDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllTopupRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	topups, errResp := r.TopupGraphql.TopupClient.TopupQueryClient.FindByTrashed(ctx, reqService)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TopupGraphql.Mapping.ToGraphqlResponsePaginationTopupDeleteAt(topups)

	return so, nil
}
