package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	graphqlerror "github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-payment-gateway-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-payment-gateway-pb/transaction"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.APIResponseTransaction, error) {
	_, err := r.TransactionGraphql.Permission.ValidateMerchant(ctx, input.APIKey)

	if err != nil {
		return nil, fmt.Errorf("failed to validate API key: %w", err)
	}

	transactionTime, err := time.Parse("2006-01-02", *input.TransactionTime)
	merchantId := int(input.MerchantID)

	if err != nil {
		return nil, fmt.Errorf("invalid date format for transactionTime: %v (expected YYYY-MM-DD)", err)
	}
	req := &pb.CreateTransactionRequest{
		ApiKey:          input.APIKey,
		CardNumber:      input.CardNumber,
		Amount:          int32(input.Amount),
		PaymentMethod:   input.PaymentMethod,
		MerchantId:      int32(merchantId),
		TransactionTime: timestamppb.New(transactionTime),
	}

	res, errResp := r.TransactionGraphql.TransactionClient.TransactionCommandClient.CreateTransaction(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)

	return so, nil
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, input model.UpdateTransactionInput) (*model.APIResponseTransaction, error) {
	id := int32(input.TransactionID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransactionInvalidID
	}

	_, err := r.TransactionGraphql.Permission.ValidateMerchant(ctx, input.APIKey)

	if err != nil {
		return nil, fmt.Errorf("failed to validate API key: %w", err)
	}

	transactionTime, err := time.Parse("2006-01-02", *input.TransactionTime)
	merchantId := int32(input.MerchantID)

	if err != nil {
		return nil, fmt.Errorf("invalid date format for transactionTime: %v (expected YYYY-MM-DD)", err)
	}
	req := &pb.UpdateTransactionRequest{
		TransactionId:   id,
		CardNumber:      input.CardNumber,
		Amount:          int32(input.Amount),
		PaymentMethod:   input.PaymentMethod,
		MerchantId:      merchantId,
		TransactionTime: timestamppb.New(transactionTime),
	}

	res, errResp := r.TransactionGraphql.TransactionClient.TransactionCommandClient.UpdateTransaction(ctx, req)

	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)

	return so, nil
}

// TrashedTransaction is the resolver for the trashedTransaction field.
func (r *mutationResolver) TrashedTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	id := int32(input.TransactionID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransactionInvalidID
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.TrashedTransaction(ctx, &pb.FindByIdTransactionRequest{
		TransactionId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)

	return so, nil
}

// RestoreTransaction is the resolver for the restoreTransaction field.
func (r *mutationResolver) RestoreTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	id := int32(input.TransactionID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransactionInvalidID
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.RestoreTransaction(ctx, &pb.FindByIdTransactionRequest{
		TransactionId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)

	return so, nil
}

// DeleteTransactionPermanent is the resolver for the deleteTransactionPermanent field.
func (r *mutationResolver) DeleteTransactionPermanent(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDelete, error) {
	id := int32(input.TransactionID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransactionInvalidID
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionCommandClient.DeleteTransactionPermanent(ctx, &pb.FindByIdTransactionRequest{
		TransactionId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlTransactionDelete(res)

	return so, nil
}

// RestoreAllTransaction is the resolver for the restoreAllTransaction field.
func (r *mutationResolver) RestoreAllTransaction(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	panic(fmt.Errorf("not implemented: RestoreAllTransaction - restoreAllTransaction"))
}

// DeleteAllTransactionPermanent is the resolver for the deleteAllTransactionPermanent field.
func (r *mutationResolver) DeleteAllTransactionPermanent(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	panic(fmt.Errorf("not implemented: DeleteAllTransactionPermanent - deleteAllTransactionPermanent"))
}

// FindAllTransaction is the resolver for the findAllTransaction field.
func (r *queryResolver) FindAllTransaction(ctx context.Context, input model.FindAllTransactionInput) (*model.APIResponsePaginationTransaction, error) {
	panic(fmt.Errorf("not implemented: FindAllTransaction - findAllTransaction"))
}

// FindAllTransactionByCardNumber is the resolver for the findAllTransactionByCardNumber field.
func (r *queryResolver) FindAllTransactionByCardNumber(ctx context.Context, input model.FindAllTransactionCardNumberInput) (*model.APIResponsePaginationTransaction, error) {
	panic(fmt.Errorf("not implemented: FindAllTransactionByCardNumber - findAllTransactionByCardNumber"))
}

// FindByIDTransaction is the resolver for the findByIdTransaction field.
func (r *queryResolver) FindByIDTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransaction, error) {
	panic(fmt.Errorf("not implemented: FindByIDTransaction - findByIdTransaction"))
}

// FindMonthlyTransactionStatusSuccess is the resolver for the findMonthlyTransactionStatusSuccess field.
func (r *queryResolver) FindMonthlyTransactionStatusSuccess(ctx context.Context, input model.FindMonthlyTransactionStatusInput) (*model.APIResponseTransactionMonthStatusSuccess, error) {
	year := int32(input.Year)
	month := int32(input.Month)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidMonth
	}

	reqService := &pb.FindMonthlyTransactionStatus{
		Year:  year,
		Month: month,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindMonthlyTransactionStatusSuccess(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthStatusSuccess(res)

	return so, nil
}

// FindYearlyTransactionStatusSuccess is the resolver for the findYearlyTransactionStatusSuccess field.
func (r *queryResolver) FindYearlyTransactionStatusSuccess(ctx context.Context, input model.FindYearTransactionStatusInput) (*model.APIResponseTransactionYearStatusSuccess, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	reqService := &pb.FindYearTransactionStatus{
		Year: year,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindYearlyTransactionStatusSuccess(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearStatusSuccess(res)

	return so, nil
}

// FindMonthlyTransactionStatusFailed is the resolver for the findMonthlyTransactionStatusFailed field.
func (r *queryResolver) FindMonthlyTransactionStatusFailed(ctx context.Context, input model.FindMonthlyTransactionStatusInput) (*model.APIResponseTransactionMonthStatusFailed, error) {
	year := int32(input.Year)
	month := int32(input.Month)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidMonth
	}

	reqService := &pb.FindMonthlyTransactionStatus{
		Year:  year,
		Month: month,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindMonthlyTransactionStatusFailed(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthStatusFailed(res)

	return so, nil
}

// FindYearlyTransactionStatusFailed is the resolver for the findYearlyTransactionStatusFailed field.
func (r *queryResolver) FindYearlyTransactionStatusFailed(ctx context.Context, input model.FindYearTransactionStatusInput) (*model.APIResponseTransactionYearStatusFailed, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	reqService := &pb.FindYearTransactionStatus{
		Year: year,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindYearlyTransactionStatusFailed(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearStatusFailed(res)

	return so, nil
}

// FindMonthlyTransactionStatusSuccessByCardNumber is the resolver for the findMonthlyTransactionStatusSuccessByCardNumber field.
func (r *queryResolver) FindMonthlyTransactionStatusSuccessByCardNumber(ctx context.Context, input model.FindMonthlyTransactionStatusCardNumberInput) (*model.APIResponseTransactionMonthStatusSuccess, error) {
	year := int32(input.Year)
	month := int32(input.Month)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidMonth
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindMonthlyTransactionStatusCardNumber{
		Year:       year,
		Month:      month,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindMonthlyTransactionStatusSuccessByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthStatusSuccess(res)

	return so, nil
}

// FindYearlyTransactionStatusSuccessByCardNumber is the resolver for the findYearlyTransactionStatusSuccessByCardNumber field.
func (r *queryResolver) FindYearlyTransactionStatusSuccessByCardNumber(ctx context.Context, input model.FindYearTransactionStatusCardNumberInput) (*model.APIResponseTransactionYearStatusSuccess, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTransactionStatusCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindYearlyTransactionStatusSuccessByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearStatusSuccess(res)

	return so, nil
}

// FindMonthlyTransactionStatusFailedByCardNumber is the resolver for the findMonthlyTransactionStatusFailedByCardNumber field.
func (r *queryResolver) FindMonthlyTransactionStatusFailedByCardNumber(ctx context.Context, input model.FindMonthlyTransactionStatusCardNumberInput) (*model.APIResponseTransactionMonthStatusFailed, error) {
	year := int32(input.Year)
	month := int32(input.Month)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if month <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidMonth
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindMonthlyTransactionStatusCardNumber{
		Year:       year,
		Month:      month,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindMonthlyTransactionStatusFailedByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthStatusFailed(res)

	return so, nil
}

// FindYearlyTransactionStatusFailedByCardNumber is the resolver for the findYearlyTransactionStatusFailedByCardNumber field.
func (r *queryResolver) FindYearlyTransactionStatusFailedByCardNumber(ctx context.Context, input model.FindYearTransactionStatusCardNumberInput) (*model.APIResponseTransactionYearStatusFailed, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindYearTransactionStatusCardNumber{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsStatus.FindYearlyTransactionStatusFailedByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearStatusFailed(res)

	return so, nil
}

// FindMonthlyPaymentMethods is the resolver for the findMonthlyPaymentMethods field.
func (r *queryResolver) FindMonthlyPaymentMethods(ctx context.Context, input model.FindYearTransactionStatusInput) (*model.APIResponseTransactionMonthMethod, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsMethod.FindMonthlyPaymentMethods(ctx, &pb.FindYearTransactionStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthMethod(res)

	return so, nil
}

// FindYearlyPaymentMethods is the resolver for the findYearlyPaymentMethods field.
func (r *queryResolver) FindYearlyPaymentMethods(ctx context.Context, input model.FindYearTransactionStatusInput) (*model.APIResponseTransactionYearMethod, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsMethod.FindYearlyPaymentMethods(ctx, &pb.FindYearTransactionStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearMethod(res)

	return so, nil
}

// FindMonthlyAmounts is the resolver for the findMonthlyAmounts field.
func (r *queryResolver) FindMonthlyAmounts(ctx context.Context, input model.FindYearTransactionStatusInput) (*model.APIResponseTransactionMonthAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsAmount.FindMonthlyAmounts(ctx, &pb.FindYearTransactionStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthAmount(res)

	return so, nil
}

// FindYearlyAmounts is the resolver for the findYearlyAmounts field.
func (r *queryResolver) FindYearlyAmounts(ctx context.Context, input model.FindYearTransactionStatusInput) (*model.APIResponseTransactionYearAmount, error) {
	year := int32(input.Year)

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsAmount.FindYearlyAmounts(ctx, &pb.FindYearTransactionStatus{
		Year: year,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearAmount(res)

	return so, nil
}

// FindMonthlyPaymentMethodsByCardNumber is the resolver for the findMonthlyPaymentMethodsByCardNumber field.
func (r *queryResolver) FindMonthlyPaymentMethodsByCardNumber(ctx context.Context, input model.FindByYearCardNumberTransactionInput) (*model.APIResponseTransactionMonthMethod, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindByYearCardNumberTransactionRequest{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsMethod.FindMonthlyPaymentMethodsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthMethod(res)

	return so, nil
}

// FindYearlyPaymentMethodsByCardNumber is the resolver for the findYearlyPaymentMethodsByCardNumber field.
func (r *queryResolver) FindYearlyPaymentMethodsByCardNumber(ctx context.Context, input model.FindByYearCardNumberTransactionInput) (*model.APIResponseTransactionYearMethod, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindByYearCardNumberTransactionRequest{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsMethod.FindYearlyPaymentMethodsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearMethod(res)

	return so, nil
}

// FindMonthlyAmountsByCardNumber is the resolver for the findMonthlyAmountsByCardNumber field.
func (r *queryResolver) FindMonthlyAmountsByCardNumber(ctx context.Context, input model.FindByYearCardNumberTransactionInput) (*model.APIResponseTransactionMonthAmount, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindByYearCardNumberTransactionRequest{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsAmount.FindMonthlyAmountsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionMonthAmount(res)

	return so, nil
}

// FindYearlyAmountsByCardNumber is the resolver for the findYearlyAmountsByCardNumber field.
func (r *queryResolver) FindYearlyAmountsByCardNumber(ctx context.Context, input model.FindByYearCardNumberTransactionInput) (*model.APIResponseTransactionYearAmount, error) {
	year := int32(input.Year)
	cardNumber := input.CardNumber

	if year <= 0 {
		return nil, graphqlerror.ErrGraphqlInvalidYear
	}

	if cardNumber == "" {
		return nil, graphqlerror.ErrGraphqlInvalidCardNumber
	}

	reqService := &pb.FindByYearCardNumberTransactionRequest{
		Year:       year,
		CardNumber: cardNumber,
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionStatsAmount.FindYearlyAmountsByCardNumber(ctx, reqService)

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionYearAmount(res)

	return so, nil
}

// FindTransactionByMerchantID is the resolver for the findTransactionByMerchantId field.
func (r *queryResolver) FindTransactionByMerchantID(ctx context.Context, input model.FindTransactionByMerchantIDInput) (*model.APIResponseTransactions, error) {
	id := int32(input.MerchantID)

	if id == 0 {
		return nil, graphqlerror.ErrGraphqlTransactionInvalidMerchantID
	}

	res, err := r.TransactionGraphql.TransactionClient.TransactionQueryClient.FindTransactionByMerchantId(ctx, &pb.FindTransactionByMerchantIdRequest{
		MerchantId: id,
	})

	if err != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactions(res)

	return so, nil
}

// FindByActiveTransaction is the resolver for the findByActiveTransaction field.
func (r *queryResolver) FindByActiveTransaction(ctx context.Context, input model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByActiveTransaction - findByActiveTransaction"))
}

// FindByTrashedTransaction is the resolver for the findByTrashedTransaction field.
func (r *queryResolver) FindByTrashedTransaction(ctx context.Context, input model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByTrashedTransaction - findByTrashedTransaction"))
}
